### PR TITLE
Slack fixes

### LINKED ISSUE #62: Add Slackbot notification when project has been claimed by copilot
Would be good to let copilots know when a project is no longer available, so they don't need to click through unnecessarily

### PR DESCRIPTION
**Pull request by uttpal**
fixed #62 #63 #65 #45

### CODE REVIEW

File: src/common/constants.js [hunk 1]
```diff
@@ -40,24 +40,74 @@ module.exports = {
             },
             {
               title: 'Owner',
-              value: `${_.get(data, 'owner.firstName', '')} ${_.get(data, 'owner.lastName', '')}` ,
+              value: `${_.get(data, 'owner.firstName', '')} ${_.get(data, 'owner.lastName', '')}`,
+              short: false,
+            },
+            {
+              title: 'Project Type',
+              value: data.project.type,
```
Comment (parthshah) [inline src/common/constants.js]: Please map raw project types to the following - 
* app_dev --> Full App
* generic --> Work Project
* visual_prototype --> Design & Prototype
* Visual Design -->  Design

File: src/common/constants.js [hunk 2]
```diff
@@ -40,24 +40,74 @@ module.exports = {
...
               short: false,
             },
           ],
         };
       },
       projectUnclaimed: (data) => {
         return {
+          icon_url: 'https://emoji.slack-edge.com/T03R80JP7/coder-the-bot/85ae574c0c7063ef.png',
```
Comment (parthshah) [inline src/common/constants.js]: please move to constants file, 'CoderBotIcon'

File: src/common/constants.js [hunk 3]
```diff
@@ -40,24 +40,74 @@ module.exports = {
...
           title: _.get(data, 'project.name', ''),
           title_link: `https://connect.${config.get('AUTH_DOMAIN')}/projects/${data.project.id}/`,
-          text: _.truncate(_.get(data, 'project.description', ''), {length: 200, separator: /,? +.,/ }),
+          text: _.truncate(_.get(data, 'project.description', ''), { length: 200, separator: /,? +.,/ }),
           ts: (new Date(_.get(data, 'project.updatedAt', null))).getTime() / 1000,
-          fields: []
+          fields: [
+            {
+              title: 'Project Type',
+              value: data.project.type,
```
Comment (parthshah) [inline src/common/constants.js]: See above, thanks!

File: src/common/constants.js [hunk 4]
```diff
@@ -40,24 +40,74 @@ module.exports = {
...
+              short: false,
+            },
+          ]
         }
-      }
+      },
+      projectUnclaimedReposted: (data) => {
+        return {
+          icon_url: 'https://emoji.slack-edge.com/T03R80JP7/coder-error/cd2633216e7fd385.png',
```
Comment (parthshah) [inline src/common/constants.js]: Move to constants CoderErrorIcon

File: src/common/constants.js [hunk 5]
```diff
@@ -40,24 +40,74 @@ module.exports = {
...
+          pretext: 'We\'re still looking for a copilot for a reviewed project. Please check it out and claim it.',
+          fallback: 'We\'re still looking for a copilot for a reviewed project. Please check it out and claim it.',
+          title: _.get(data, 'project.name', ''),
+          title_link: `https://connect.${config.get('AUTH_DOMAIN')}/projects/${data.project.id}/`,
+          text: _.truncate(_.get(data, 'project.description', ''), { length: 200, separator: /,? +.,/ }),
+          ts: (new Date(_.get(data, 'project.updatedAt', null))).getTime() / 1000,
+          fields: [
+            {
+              title: 'Project Type',
+              value: data.project.type,
```
Comment (parthshah) [inline src/common/constants.js]: Same as above

File: src/common/constants.js [hunk 6]
```diff
@@ -40,24 +40,74 @@ module.exports = {
...
+              short: false,
+            },
+          ]
+        }
+      },
+      projectClaimed: (data) => {
+        return {
+          icon_url: 'https://emoji.slack-edge.com/T03R80JP7/coder-grinning/a3b7f3fe9e838377.png',
```
Comment (parthshah) [inline src/common/constants.js]: Move to constants - CoderGrinningIcon
